[package]
name = "cosmos-vault-standard"
version = "0.1.0"
edition = "2021"
authors = ["Sturdy <sturdy@apollo.farm>"]

[features]
default = []
lockup = ["cw-utils"]
keeper = []
cw20 = ["dep:cw20", "dep:cw-asset"]
cw4626 = ["cw20"]

[dependencies]
cosmwasm-std = "1.1.0"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
cosmwasm-schema = { version = "1.1.0" }
cw-utils = { version = "0.16.0", optional = true }
cw20 = { version = "0.16.0", optional = true }
cw-asset = { version = "2.3.0", optional = true }
