[workspace]
members = [
    "contracts/account-nft",
    "contracts/credit-manager",
    "contracts/swapper/*",
    "contracts/oracle-adapter",
    "packages/*",

#    Mock contracts
    "contracts/mock-oracle",
    "contracts/mock-red-bank",
    "contracts/mock-vault",
]

[profile.release.package.rover]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
