[workspace]
members = [
    # prod contracts
    "contracts/account-nft",
    "contracts/credit-manager",
    "contracts/swapper/*",
    "contracts/v2-zapper/*",
    "contracts/v3-zapper/*",
    "contracts/health",

    # mock contracts
    "contracts/mock-credit-manager",
    "contracts/mock-health",
    "contracts/mock-oracle",
    "contracts/mock-red-bank",
    "contracts/mock-vault",

    # packages
    "packages/health-computer",
    "packages/health-types",
    "packages/rover",
]

[workspace.package]
version       = "2.0.0"
authors       = [
  "Gabe R. <gabe.r@delphilabs.io>",
  "Larry Engineer <larry@delphidigital.io>",
  "Piotr Babel <piotr@delphilabs.io>",
]
license       = "GPL-3.0-or-later"
edition       = "2021"
repository    = "https://github.com/mars-protocol/rover"
homepage      = "https://marsprotocol.io"
documentation = "https://docs.marsprotocol.io/"
keywords      = ["mars", "cosmos", "cosmwasm"]

[workspace.dependencies]
anyhow             = "1.0.71"
cosmwasm-schema    = "1.2.5"
cosmwasm-std       = "1.2.5"
cw2                = "1.0.1"
cw721              = { git = "https://github.com/CosmWasm/cw-nfts/", branch = "main" }
cw721-base         = { git = "https://github.com/CosmWasm/cw-nfts/", branch = "main", features = ["library"] }
cw-multi-test      = "0.16.4"
cw-paginate        = "0.2.1"
cw-utils           = "1.0.1"
cw-storage-plus    = "1.0.1"
itertools          = "0.10.5"
osmosis-std        = { git = "https://github.com/osmosis-labs/osmosis-rust", branch = "main" }
osmosis-test-tube  = { git = "https://github.com/osmosis-labs/test-tube", branch = "main" }
schemars           = "0.8.12"
serde              = { version = "1.0.160", default-features = false, features = ["derive"] }
serde_json         = "1.0.96"
serde-wasm-bindgen = "0.5.0"
thiserror          = "1.0.40"
wasm-bindgen       = "0.2.84"

# packages
cw-dex                     = { version = "0.1.3", features = ["osmosis"] }
cw-vault-standard          = { version = "0.3.0", features = ["lockup", "force-unlock"] }
mars-rover-health-computer = { version = "2.0.0", path = "./packages/health-computer" }
mars-rover-health-types    = { version = "2.0.0", path = "./packages/health-types" }
mars-osmosis               = { git = "https://github.com/mars-protocol/red-bank", rev = "00301d60c38af09d8eb7980355009e2f00c6f41f" }
mars-red-bank-types        = "1.0.0"
mars-owner                 = { version = "1.1.0", features = ["emergency-owner"] }
mars-params                = "1.0.2"
mars-rover                 = { version = "2.0.0", path = "./packages/rover" }

# contracts
mars-account-nft    = { version = "2.0.0", path = "./contracts/account-nft", features = ["library"] }
mars-rover-health   = { version = "2.0.0", path = "./contracts/health" }
mars-swapper-base   = { version = "2.0.0", path = "./contracts/swapper/base" }
mars-v2-zapper-base = { version = "2.0.0", path = "./contracts/v2-zapper/base" }
mars-v3-zapper-base = { version = "2.0.0", path = "./contracts/v3-zapper/base" }

# mocks
mars-mock-credit-manager = { version = "2.0.0", path = "./contracts/mock-credit-manager", features = ["library"] }
mars-mock-oracle         = { version = "2.0.0", path = "./contracts/mock-oracle", features = ["library"] }
mars-mock-red-bank       = { version = "2.0.0", path = "./contracts/mock-red-bank", features = ["library"] }
mars-mock-vault          = { version = "2.0.0", path = "./contracts/mock-vault", features = ["library"] }
mars-mock-rover-health   = { version = "2.0.0", path = "./contracts/mock-health", features = ["library"] }
mars-swapper-mock        = { version = "2.0.0", path = "./contracts/swapper/mock", features = ["library"] }
mars-v2-zapper-mock      = { version = "2.0.0", path = "./contracts/v2-zapper/mock", features = ["library"] }

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
overflow-checks  = true
opt-level        = 3
panic            = "abort"
rpath            = false
