comment: false

coverage:
  status:
    project:
      default:
        threshold: 0.05%
    patch:
      default:
        threshold: 0.05%

ignore:
# ignore code coverage on following paths
#  - "**/tests"
#  - "**/benches"
#  - "**/examples"