extend= [
    { path = "schema.Makefile.toml" },
    { path = "coverage_grcov.Makefile.toml" }
]

[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--locked"]

[tasks.rust-optimizer]
script = """
if [[ $(arch) == "arm64" ]]; then
  image="cosmwasm/workspace-optimizer-arm64:0.12.8"
else
  image="cosmwasm/workspace-optimizer:0.12.10"
fi
docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  ${image}
"""

[tasks.test]
command = "cargo"
args = ["test", "--locked"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--tests", "--", "-D", "warnings"]

[tasks.audit]
command = "cargo"
args = ["audit"]

[tasks.coverage]
dependencies = ["coverage_grcov"]

[tasks.all-actions]
dependencies = [
    "fmt",
    "clippy",
    "build",
    "test",
    "generate-all-schemas",
    "audit",
    "rust-optimizer",
]
