extend = [
    { path = "schema.Makefile.toml" },
    { path = "coverage_grcov.Makefile.toml" }
]

[config]
default_to_workspace = false

[env]
# Directory with wasm files used by integration tests (another directory can be used instead, for example 'artifacts' from rust-optimizer)
ARTIFACTS_DIR_PATH = "artifacts"

[tasks.build]
command = "cargo"
# TODO: After stable osmosis-test-tube CL version, remove the exclusion
args = ["build", "--release", "--target", "wasm32-unknown-unknown", "--locked", "--exclude", "mars-v3-zapper-osmosis", "--workspace"]

[tasks.rust-optimizer]
script = """
if [[ $(arch) == "arm64" ]]; then
  image="cosmwasm/workspace-optimizer-arm64:0.12.13"
else
  image="cosmwasm/workspace-optimizer:0.12.13"
fi
docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  ${image}
"""

[tasks.test]
command = "cargo"
# TODO: After stable osmosis-test-tube CL version, remove the exclusion
args = ["test", "--locked", "--exclude", "mars-v3-zapper-osmosis", "--workspace"]

[tasks.fmt]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--all", "--check"]

[tasks.clippy]
command = "cargo"
# TODO: After stable osmosis-test-tube CL version, remove the exclusion
args = ["clippy", "--tests", "--exclude", "mars-v3-zapper-osmosis", "--workspace", "--", "-D", "warnings"]

[tasks.audit]
command = "cargo"
args = ["audit"]

[tasks.coverage-html]
alias = "coverage-grcov-html"

[tasks.coverage-lcov]
alias = "coverage-grcov-lcov"

[tasks.all-actions]
dependencies = [
    "fmt",
    "clippy",
    "build",
    "test",
    "generate-all-schemas",
    "audit",
    "rust-optimizer",
]
