[package]
name = "rover"
version = "0.1.0"
authors = ["larry_0x <larry@delphidigital.io>", "Gabe R. <gabe.r@delphilabs.io>"]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/mars-protocol/rover"

[lib]
doctest = false

[dependencies]
mars-health = { version = "0.1", path = "../../../outposts/packages/health" }
mars-outpost = { version = "0.1", path = "../../../outposts/packages/outpost" }
mock-red-bank = { version = "1.0", path = "../../contracts/mock-red-bank", features = ["library"] }
mock-oracle = { version = "1.0", path = "../../contracts/mock-oracle", features = ["library"] }

cosmwasm-std = "1.0"
cw-storage-plus = "0.14"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
thiserror = "1.0"
