[package]
name          = "mars-rover"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }
keywords      = { workspace = true }

[lib]
doctest = false

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmos-vault-standard = { workspace = true }
cosmwasm-schema       = { workspace = true }
cosmwasm-std          = { workspace = true }
cw-storage-plus       = { workspace = true }
cw-utils              = { workspace = true }
mars-health           = { workspace = true }
mars-mock-oracle      = { workspace = true }
mars-mock-red-bank    = { workspace = true }
mars-outpost          = { workspace = true }
schemars              = { workspace = true }
serde                 = { workspace = true }
thiserror             = { workspace = true }
