[package]
name = "credit-manager"
version = "1.0.0"
authors = ["grod220 <gabe.r@delphilabs.io>, larry_0x <larry@delphidigital.io>"]
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/mars-protocol/rover"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
account-nft = { version = "1.0", path = "../account-nft", features = ["library"] }
mars-health = { version = "0.1", path = "../../../outposts/packages/health" }
mock-oracle = { version = "1.0", path = "../../contracts/mock-oracle", features = ["library"] }
mars-oracle-adapter = { version = "1.0", path = "../../contracts/mars-oracle-adapter", features = ["library"] }
mock-red-bank = { version = "1.0", path = "../../contracts/mock-red-bank", features = ["library"] }
mock-vault = { version = "1.0", path = "../../contracts/mock-vault", features = ["library"] }
rover = { version = "1.0", path = "../../packages/rover" }

cosmwasm-schema = "1.1"
cosmwasm-std = "1.1"
cw2 = "0.16"
cw721 = "0.15"
cw721-base = { version = "0.15", features = ["library"] }
cw-storage-plus = "0.16"

[dev-dependencies]
swapper-mock = { version = "1.0", path = "../../contracts/swapper/mock", features = ["library"] }
mars-outpost = { version = "0.1", path = "../../../outposts/packages/outpost" }

anyhow = "1"
cw-multi-test = "0.16"
itertools = "0.10"
