[package]
name          = "hello-wasm"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { workspace = true }
