name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  RUST_BACKTRACE: 1
  # Directory with wasm files used by `tests`
  ARTIFACTS_DIR_PATH: 'target/wasm32-unknown-unknown/release'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
          profile: minimal
          override: true

      # selecting a toolchain should happen before the plugin, as the cache uses the current rustc version as its cache key
      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Compile workspace
        run: cargo build --release --target wasm32-unknown-unknown --locked

      #- name: Compile contracts to wasm
      #  run: cargo make rust-optimizer

      - name: Lint
        run: |
          cargo fmt --all --check
          cargo clippy --tests -- -D warnings

      - name: Run tests
        run: cargo test --locked

      #- name: Generate schemas
      #  run: cargo make generate-all-schemas
