# disabled because `cargo tarpaulin` currently segfaults

name: Coverage

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  # job currently (1st Feb 2022) segfaults
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-x86_64-unknown-linux-gnu
          profile: minimal
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Generate coverage file
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --workspace --out Xml --verbose
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}