on: pull_request

name: Main

env:
  # Directory with wasm files used by `tests`
  ARTIFACTS_DIR_PATH: 'target/wasm32-unknown-unknown/release'

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Compile workspace
        run: cargo make build

      - name: Compile contracts to wasm
        run: cargo make rust-optimizer

      - name: Generate schemas
        run: cargo make generate-all-schemas

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Compile workspace
        run: cargo make build

      - name: Run tests
        run: cargo make test

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Check formatting
        run: cargo make fmt

      - name: Clippy check
        run: cargo make clippy

